#!/usr/bin/env bash

tmpfile=$(mktemp /tmp/solcmc_regression.XXXXXX)

docker run -it --rm --user $(id -u):$(id -g) -v $(pwd):/smtch --workdir /smtch leoalt/cav:latest /bin/sh run_solcmc_regression $@ &> "$tmpfile"

cat "$tmpfile"

tmpjson="$tmpfile.json"

tail -1 "$tmpfile" > "$tmpjson"

python3 ./regression_format.py "$tmpjson" $1
