FROM ubuntu:20.04

ARG ELDARICA_VERSION

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y gnupg

RUN echo "deb http://ppa.launchpad.net/ethereum/cpp-build-deps/ubuntu focal main" >> /etc/apt/sources.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1c52189c923f6ca9 \
    && apt-get update        \
    && apt-get install -y \
    wget                  \
    zip                   \
    default-jre-headless  \
    curl                  \
    git                   \
		z3-static             \
    && apt-get clean

# Download nodejs and npm

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN    apt-get update               \
    && apt-get upgrade --yes        \
    && apt-get install --yes nodejs

# Set up Eldarica

COPY eldarica /home/eldarica

ENV PATH="/home/eldarica:$PATH"

# Download solcjs and ts-node

RUN cd /home/                                                            \
    && git clone --branch master https://github.com/ethereum/solc-js.git \
    && cd /home/solc-js/                                                 \
    && npm install                                                       \
    && npm install -g ts-node

RUN sed -i 's/const timeout = 10000;/const timeout = 3600000;/g' /home/solc-js/smtsolver.ts
RUN sed -i 's/rlimit=20000000//g' /home/solc-js/smtsolver.ts

COPY run.ts /home/solc-js/
COPY run_all_solvers.ts /home/solc-js/
COPY soljson_cex.js /home/solc-js/soljson.js
