FROM archlinux:latest

ARG ELDARICA_VERSION

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN pacman --noconfirm -Syu --noprogressbar --needed z3 git jre-openjdk-headless curl

# Download nodejs and npm

RUN touch ~/.bashrc
RUN pacman --noconfirm -S --noprogressbar nodejs npm

RUN source ~/.bashrc

# Set up Eldarica

COPY eldarica /home/eldarica

ENV PATH="/home/eldarica:$PATH"

# Download solcjs and ts-node

RUN npm install -g ts-node

RUN cd /home/                                                            \
    && git clone --branch cav_artifact https://github.com/ethereum/solc-js.git \
    && cd /home/solc-js/                                                 \
    && npm install

COPY regression /home/solc-js/regression

COPY run.ts /home/solc-js/
COPY run_all_solvers.ts /home/solc-js/
COPY run_regression.ts /home/solc-js/
COPY soljson.js /home/solc-js/soljson.js
