#!/usr/bin/env bash

table="Category\t\tTotal\t\tEldarica\t\tSpacer Quant"
for dir in ./regression/*
do
	cat=$(basename $dir)
	res=$(tail -1 "tests/regression/$cat.txt")
	table="$table\n$res"
done

printf "$table"
